### ISSUE TITLE
'You have undefined unread undefined'

### ISSUE THREAD

**Issue by hyamdev** [htilly/zenmusic#10]
Hey,

I tried to set up this integration, but I keep having this `You have undefined unread undefined` error when I try to run the `node index.js` command. 

Any solution?
Thanks.

**Comment by johanhessler** [comment]
I have the same issue on win10, quite sure i got it to work on linux though (just for info)

**Comment by hyamdev** [comment]
I already running it on Ubuntu. Tried on macOS, but the same error comes up

**Comment by htilly** [comment]
Hi! 

I just removed the line causing this. It should still work thou even if the error occurs.

BR
Tilly
