### ISSUE TITLE
Playlist functionality

### ISSUE THREAD

**Issue by ow** [htilly/zenmusic#13]
This is awesome! I wondered if you considered/messed around with adding the ability to throw in playlists from Spotify too? It looks like it could be quite complicated, but also doable...

**Comment by htilly** [comment]
Hi!
Glad you like it. Yes, we have considered this but it´s still on the to-do list.
"When local playlist is empty -> fallback and start playing "$playlist", i.e. Spotify topp 100."

Please feel free to add functionality or modify the code.

We love PR =)

BR
Tilly

**Comment by htilly** [comment]
Hi!
This is now implemented. Also support for "bestof" =)
