### ISSUE TITLE
Error 500 on adding song

### ISSUE THREAD

**Issue by laurensV** [htilly/zenmusic#16]
Adding a song to the queue gives this error:
`Error: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#AddURIToQueue"`

Even though my index.js contains the fix that is suppose to fix the 500 problem..
```
// Old version.. New is supposed to fix 500 problem...
// sonos.addSpotifyQueue(spid, function (err, res) {
sonos.addSpotify(spid, function (err, res) {
```

**Comment by laurensV** [comment]
When I revert the 'fix' the 500 error is gone :)

**Comment by htilly** [comment]
Yea..  can´t figure this one out..  
Seems that different models response differently.

/Tilly
