### ISSUE TITLE
Play command will always play the first song from the queue

### ISSUE THREAD

**Issue by laurensV** [htilly/zenmusic#17]
Isn't it better to play the song where it last ended from the queue? Is there also the possibility to play a certain song from the queue (or a new song) directly?

**Comment by htilly** [comment]
Hi!

Play, stop and pause is admin command and shouldn't´t be used for regular used.

"add" will add a song to the queue if the unit is already playing a tune.
If the unit is idle, add will flush the old queue and start from fresh.

Append only works if the unit is idle. It will then reuse the previous queue, start playing it and add the new song to the end of the queue.

If you want to play a new song directly, use the flush command, then add (flush is admin).

BR
Tilly

**Comment by laurensV** [comment]
But there is no way to pause the music and start playing again.. There is no 'pause' command and when you do 'stop' and then 'play' it will start playing the queue from the start. I think it is better to:

- create a 'pause' command that pauses the music
- remove the stop command (what is the use of the stop command?)
- let the 'play' command resume the music
- create an extra command 'replay' to start the queue from the start

**Comment by htilly** [comment]
well..  made a quick hack..

try the following commands:
pause
playpause

**Comment by laurensV** [comment]
Thanks! However, the playpause command is exactly the same as the play command and starts playing the queue from the top instead of resuming the song. Pause command is working.

**Comment by laurensV** [comment]
Sometimes the playpause function resumes the song, and then the next time it will play the list from the start. Can't figure this out yet..
