### ISSUE TITLE
Spotify Issues...

### ISSUE THREAD

**Issue by apanzerj** [htilly/zenmusic#19]
Hey! 

Great bot. We started using it today but I noticed I can't do spotify searches or adds. I get this error:

```
Received: message #music-admin @panzer 1495833390.986118 "append The Rockafeller Skank"
term append
/opt/zenmusic/node_modules/urllib-sync/index.js:40
    throw res.error;
    ^

Error: spawnSync /usr/local/bin/node ETIMEDOUT
    at exports._errnoException (util.js:1050:11)
    at Object.spawnSync (child_process.js:459:20)
    at Object.request (/opt/zenmusic/node_modules/urllib-sync/index.js:33:16)
    at _append (/opt/zenmusic/index.js:616:29)
    at RTMClient.slack.on (/opt/zenmusic/index.js:148:21)
    at RTMClient.emit (/opt/zenmusic/node_modules/eventemitter3/index.js:116:35)
    at RTMClient.emit (/opt/zenmusic/node_modules/@slack/client/lib/clients/client.js:82:39)
    at RTMClient._handleWsMessageViaEventHandler (/opt/zenmusic/node_modules/@slack/client/lib/clients/rtm/client.js:472:10)
    at RTMClient.handleWsMessage (/opt/zenmusic/node_modules/@slack/client/lib/clients/rtm/client.js:426:10)
    at WebSocket.wrapper (/opt/zenmusic/node_modules/lodash/lodash.js:4968:19)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:194:7)
    at Receiver.ontext (/opt/zenmusic/node_modules/ws/lib/WebSocket.js:841:10)
    at /opt/zenmusic/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/opt/zenmusic/node_modules/ws/lib/Receiver.js:371:5)
    at /opt/zenmusic/node_modules/ws/lib/Receiver.js:508:14

```

Is there more config needed?

**Comment by htilly** [comment]
Hmm..  I assume the sonos is configured correctly with Spotify and works standalone?

What version of node are you running?
No firewalls blocking the communication ?
What platform are you running it on? OSX?
BR
Tilly

**Comment by apanzerj** [comment]
Thanks for getting back to me.

I'm using a Raspberry Pi. 

```
pi@raspberrypi:/opt/zenmusic $ node --version
v7.10.0
pi@raspberrypi:/opt/zenmusic $ npm --version
4.6.1
```

No firewalls and the Sonos itself works just fine.

**Comment by apanzerj** [comment]
To be honest, I also tried this on my mac and had the same exact problem.z

**Comment by apanzerj** [comment]
@htilly just pinging you to see if you saw my response.

thanks

ajp

**Comment by htilly** [comment]
Hi! Did see the response.
Do you still have the same problem after the implementation of Spotify key?
(see README for more info).

However, I don´t think that is the problem since it´s RTMClient that seems to have problems. And that is the function of actually communication with Slack :/

BR
Tilly

**Comment by htilly** [comment]
Have you checked firewalls etc?
Tried from another network ?

**Comment by apanzerj** [comment]
Checking. Not sure what you mean by spotify key.

**Comment by apanzerj** [comment]
So where does the spotify token actually go?

**Comment by apanzerj** [comment]
Figured it out. Works now! Thanks :-D

**Comment by htilly** [comment]
Spotify recently changed so that you need a API key to do search etc.
To get the keys, log in to Spotify and go to:
https://developer.spotify.com/my-applications/#!/applications
Create an app and get the two values:
Client ID and Client Secret.

When you have received these values, encode them with Base64.
Head over to https://www.base64encode.org and decode to base64.

You should paste something like:
dfh543455dfgr44455dfgbgd4544fff:r55666655444333fbg332de34f444f4r
(note the : between ClientID and Client Secret)

You should now have received something like:
GhgyGKHJK45HJKHSDdvkjhKJHkjhdfkjKJHkjh334kjhKJhkjdh777JKJHCXKJCJKkj234kjkjhKJHkjhdcvdcj=

Put this value in the config.json as "apiKey":
"apiKey": ""

BR
Tilly

**Comment by anthonyangel** [comment]
@apanzerj what was the fix for this? I'm having the same issues

**Comment by apanzerj** [comment]
I also had issues with the IP of the sonos speakers changing too

**Comment by apanzerj** [comment]
but that's all I remember. I no longer work at a company with Sonos Speakers ¯\_(ツ)_/¯

**Comment by htilly** [comment]
Quick question @anthonyangel
Are you using a US or Non US spotify account?

**Comment by anthonyangel** [comment]
I'm in the UK, I've set market=GB in config

**Comment by htilly** [comment]
Ok, just to make sure, have you changed the following lines in index.js ?

// Old version..  New is supposed to fix 500 problem...
                            // sonos.addSpotifyQueue(spid, function (err, res) {

                            sonos.addSpotify(spid, function (err, res) {

If Non US, try the OLD version..  
So your code should be:

// Old version..  New is supposed to fix 500 problem...
                            sonos.addSpotifyQueue(spid, function (err, res) {

                            // sonos.addSpotify(spid, function (err, res) {

Note that you need to change this in multiple places in the index.js
I know.. should really fix the code so it autodetect what region...

BR
Tilly
