### ISSUE TITLE
index.js says "Online!" but says nothing else

### ISSUE THREAD

**Issue by theskyfloor** [htilly/zenmusic#37]
hi, love this script! i am trying to set up a new instance. when i run the script i get this in response and nothing else:

``` node index.js
warn: SlackDataStore is deprecated and will be removed in the next major version. See project documentation for a migration guide.
06-18 14:35:34:634   Online!
```

any tips would be appreciated!

**Comment by htilly** [comment]
Hi!
That is expect. Code needs to be updated to latest API for slack. But it should still work.

**Comment by htilly** [comment]
Does the script work except for the output?

**Comment by theskyfloor** [comment]
Totally. I ended up getting it to run! The main issue I am still having is connecting to Sonos. I am running Zenmusic on a remote server. So I need to forward a port on my local network so that I can connect to the Sonos remotely correct? Was the script designed to be run locally?

**Comment by htilly** [comment]
Good to hear!
Yes, the script is designed to run locally. But as you say, it can be deployed remotely but then you have to solve the networking issue since it is using the Sonos API to control the unit.

I know that some are running the code on Heroku.

**Comment by theskyfloor** [comment]
Yeah, I saw that. Interesting. Thanks for responding 💯

**Comment by htilly** [comment]
Sorry for the late answer :-) Closing the case.
