### ISSUE TITLE
crash when adding music / package.json not up-to-date ?

### ISSUE THREAD

**Issue by JeromeBouvard** [htilly/zenmusic#4]
Hi !
i am trying to set up the server in our office.

1/ it seems that the package.json is not up-to-date, as the node-sonos is still on 0.11.x.
2/ if I update the node-sones library , it crashes.

Could you try to do your sequence on a brand new fresh computer ? I tried on 3 different and have same result : 

git clone https://github.com/htilly/zenmusic
cd zenmusic
npm install (should be wrong due to bad version of node-sonos)
Change all the values in "config.json".
node index.js

nothing else to do ? patching some files ?

thanks !

**Comment by htilly** [comment]
Hi!

Strange. "Should" work =)
Tried it on a clean mac. Got the following output:

Make sure you are running v6.

`TillysiMac:zenmusic tilly$ node -v
v6.3.1`

`TillysiMac:dev tilly$ git clone https://github.com/htilly/zenmusic.git
Cloning into 'zenmusic'tilly...
remote: Counting objects: 2110, done.
remote: Total 2110 (delta 0), reused 0 (delta 0), pack-reused 2110
Receiving objects: 100% (2110/2110), 2.29 MiB | 967.00 KiB/s, done.
Resolving deltas: 100% (290/290), done.
Checking connectivity... done.
TillysiMac:dev tilly$ cd zenmusic/
TillysiMac:zenmusic tilly$ npm install
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
zen-music@1.0.0 /Users/tilly/Documents/dev/zenmusic
├─┬ @slack/client@3.5.3 
│ ├── async@1.5.2 
│ ├── bluebird@3.4.1 
│ ├── eventemitter3@1.2.0 
│ ├─┬ https-proxy-agent@1.0.0 
│ │ ├─┬ agent-base@2.0.1 
│ │ │ └── semver@5.0.3 
│ │ └── extend@3.0.0 
│ ├── inherits@2.0.1 
│ ├── lodash@4.14.1 
│ ├─┬ request@2.74.0 
│ │ ├── aws-sign2@0.6.0 
│ │ ├── aws4@1.4.1 
│ │ ├─┬ bl@1.1.2 
│ │ │ └─┬ readable-stream@2.0.6 
│ │ │   ├── core-util-is@1.0.2 
│ │ │   ├── isarray@1.0.0 
│ │ │   ├── process-nextick-args@1.0.7 
│ │ │   ├── string_decoder@0.10.31 
│ │ │   └── util-deprecate@1.0.2 
│ │ ├── caseless@0.11.0 
│ │ ├─┬ combined-stream@1.0.5 
│ │ │ └── delayed-stream@1.0.0 
│ │ ├── forever-agent@0.6.1 
│ │ ├── form-data@1.0.0-rc4 
│ │ ├─┬ har-validator@2.0.6 
│ │ │ ├─┬ chalk@1.1.3 
│ │ │ │ ├── ansi-styles@2.2.1 
│ │ │ │ ├── escape-string-regexp@1.0.5 
│ │ │ │ ├─┬ has-ansi@2.0.0 
│ │ │ │ │ └── ansi-regex@2.0.0 
│ │ │ │ ├── strip-ansi@3.0.1 
│ │ │ │ └── supports-color@2.0.0 
│ │ │ ├─┬ commander@2.9.0 
│ │ │ │ └── graceful-readlink@1.0.1 
│ │ │ ├─┬ is-my-json-valid@2.13.1 
│ │ │ │ ├── generate-function@2.0.0 
│ │ │ │ ├─┬ generate-object-property@1.2.0 
│ │ │ │ │ └── is-property@1.0.2 
│ │ │ │ ├── jsonpointer@2.0.0 
│ │ │ │ └── xtend@4.0.1 
│ │ │ └─┬ pinkie-promise@2.0.1 
│ │ │   └── pinkie@2.0.4 
│ │ ├─┬ hawk@3.1.3 
│ │ │ ├── boom@2.10.1 
│ │ │ ├── cryptiles@2.0.5 
│ │ │ ├── hoek@2.16.3 
│ │ │ └── sntp@1.0.9 
│ │ ├─┬ http-signature@1.1.1 
│ │ │ ├── assert-plus@0.2.0 
│ │ │ ├─┬ jsprim@1.3.0 
│ │ │ │ ├── extsprintf@1.0.2 
│ │ │ │ ├── json-schema@0.2.2 
│ │ │ │ └── verror@1.3.6 
│ │ │ └─┬ sshpk@1.9.1 
│ │ │   ├── asn1@0.2.3 
│ │ │   ├── assert-plus@1.0.0 
│ │ │   ├─┬ dashdash@1.14.0 
│ │ │   │ └── assert-plus@1.0.0 
│ │ │   ├── ecc-jsbn@0.1.1 
│ │ │   ├─┬ getpass@0.1.6 
│ │ │   │ └── assert-plus@1.0.0 
│ │ │   ├── jodid25519@1.0.2 
│ │ │   ├── jsbn@0.1.0 
│ │ │   └── tweetnacl@0.13.3 
│ │ ├── is-typedarray@1.0.0 
│ │ ├── isstream@0.1.2 
│ │ ├── json-stringify-safe@5.0.1 
│ │ ├─┬ mime-types@2.1.11 
│ │ │ └── mime-db@1.23.0 
│ │ ├── node-uuid@1.4.7 
│ │ ├── oauth-sign@0.8.2 
│ │ ├── qs@6.2.1 
│ │ ├── stringstream@0.0.5 
│ │ ├── tough-cookie@2.3.1 
│ │ └── tunnel-agent@0.4.3 
│ ├── retry@0.9.0 
│ ├── url-join@0.0.1 
│ ├─┬ winston@2.2.0 
│ │ ├── async@1.0.0 
│ │ ├── colors@1.0.3 
│ │ ├── cycle@1.0.3 
│ │ ├── eyes@0.1.8 
│ │ ├── pkginfo@0.3.1 
│ │ └── stack-trace@0.0.9 
│ └─┬ ws@1.1.1 
│   ├── options@0.0.6 
│   └── ultron@1.0.2 
├── htmlencode@0.0.4 
├─┬ sonos@0.11.1 
│ ├─┬ debug@2.2.0 
│ │ └── ms@0.7.1 
│ ├── ip@1.1.0 
│ ├─┬ request@2.67.0 
│ │ ├── bl@1.0.3 
│ │ ├── qs@5.2.1 
│ │ └── tough-cookie@2.2.2 
│ ├── underscore@1.8.3 
│ ├─┬ upnp-client@0.0.1 
│ │ └── step@0.0.6 
│ └─┬ xml2js@0.4.15 
│   ├── sax@1.2.1 
│   └── xmlbuilder@8.2.2 
├─┬ urlencode@1.1.0 
│ └── iconv-lite@0.4.13 
└─┬ urllib-sync@1.1.3 
  ├─┬ urllib@2.9.1 
  │ ├── any-promise@1.2.0 
  │ ├─┬ default-user-agent@1.0.0 
  │ │ └─┬ os-name@1.0.3 
  │ │   ├─┬ osx-release@1.1.0 
  │ │   │ └── minimist@1.2.0 
  │ │   └── win-release@1.1.1 
  │ ├─┬ digest-header@0.0.1 
  │ │ └─┬ utility@0.1.11 
  │ │   └── address@1.0.0 
  │ ├── humanize-ms@1.0.2 
  │ ├── media-typer@0.3.0 
  │ └── statuses@1.2.1 
  └─┬ utility@1.7.1 
    ├── copy-to@2.0.1 
    └── escape-html@1.0.3 `

**Comment by htilly** [comment]
Sorry. My bad. U need to add two functions to node-sonos. 
It has been added in the repro.
See:
https://github.com/bencevans/node-sonos/commit/bfb995610c8aa20bda09e370b0f5d31ba0caa6a0

So, please add the following lines in this file:
**node_modules/sonos/lib/sonos.js**

Sonos.prototype.addSpotifyQueue = function(track_id, callback) {
var rand = '00030020'
var uri = 'x-sonos-spotify:spotify%3atrack%3a' + track_id
var meta = 'dc:title/dc:titleupnp:classobject.item.audioItem.musicTrack/upnp:classSA_RINCON2311_X_#Svc2311-0-Token'

this.queue({
uri: uri,
metadata: meta
}, callback)
}

Sonos.prototype.getQueue = function (callback) {
var self = this

var defaultOptions = {
BrowseFlag: 'BrowseDirectChildren',
Filter: '*',
StartingIndex: '0',
RequestedCount: '1000',
SortCriteria: ''
}

var opts = {
ObjectID: 'Q:0'
}

opts = _.extend(defaultOptions, opts)

var contentDirectory = new Services.ContentDirectory(this.host, this.port)
return contentDirectory.Browse(opts, function (err, data) {
console.log(err)
console.log(data)
if (err) return callback(err)
return (new xml2js.Parser()).parseString(data.Result, function (err, didl) {
if (err) return callback(err, data)
var items = []
if ((!didl) || (!didl['DIDL-Lite'])) {
return callback(new Error('Cannot parse DIDTL result'), data)
}
var resultcontainer = didl['DIDL-Lite'].item
if (!util.isArray(resultcontainer)) {
return callback(new Error('Cannot parse DIDTL result'), data)
}
.each(resultcontainer, function (item) {
var albumArtURL = null
if (util.isArray(item['upnp:albumArtURI'])) {
if (item['upnp:albumArtURI'][0].indexOf('http') !== -1) {
albumArtURL = item['upnp:albumArtURI'][0]
} else {
albumArtURL = 'http://' + self.host + ':' + self.port + item['upnp:albumArtURI'][0]
}
}
items.push({
'title': util.isArray(item['dc:title']) ? item['dc:title'][0] : null,
'artist': util.isArray(item['dc:creator']) ? item['dc:creator'][0] : null,
'albumArtURL': albumArtURL,
'album': util.isArray(item['upnp:album']) ? item['upnp:album'][0] : null,
'uri': util.isArray(item.res) ? item.res[0]. : null
})
})
var result = {
returned: data.NumberReturned,
total: data.TotalMatches,
items: items
}
return callback(null, result)
})
})
}

**Comment by JeromeBouvard** [comment]
will try it next week :) thanks

**Comment by JeromeBouvard** [comment]
Progress ... but still not working
```
Received: message #music @jerome 1470063941.000024 "search adele"
term search
{ tracks: 
   { href: 'https://api.spotify.com/v1/search?query=adele&offset=0&limit=3&type=track&market=US',
     items: [ [Object], [Object], [Object] ],
     limit: 3,
     next: 'https://api.spotify.com/v1/search?query=adele&offset=3&limit=3&type=track&market=US',
     offset: 0,
     previous: null,
     total: 6580 } }
Received: message #music @jerome 1470063949.000028 "add Adele - Hello"
term add
{ tracks: 
   { href: 'https://api.spotify.com/v1/search?query=Adele+-+Hello&offset=0&limit=1&type=track&market=US',
     items: [ [Object] ],
     limit: 1,
     next: 'https://api.spotify.com/v1/search?query=Adele+-+Hello&offset=1&limit=1&type=track&market=US',
     offset: 0,
     previous: null,
     total: 163 } }
[ null, [ { '$': [Object] } ] ]
Error: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#AddURIToQueue"
    at Request._callback (/Users/jerome/Documents/zenmusic/node_modules/sonos/lib/sonos.js:97:23)
    at Request.self.callback (/Users/jerome/Documents/zenmusic/node_modules/sonos/node_modules/request/request.js:198:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/jerome/Documents/zenmusic/node_modules/sonos/node_modules/request/request.js:1035:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/jerome/Documents/zenmusic/node_modules/sonos/node_modules/request/request.js:962:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:973:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by htilly** [comment]
Strange..  
I assume the Sonos is all setup and working with Spotify if you connect directly to it?
What version of Node are you running?

`node -v`
`v6.3.0`

**Comment by htilly** [comment]
How does your config file look like?
Also, try to get the latest patch of node-sonos by typing:
`npm install https://github.com/bencevans/node-sonos.git#bfb995610c8aa20bda09e370b0f5d31ba0caa6a0  --save`

**Comment by JeromeBouvard** [comment]
config file is fine, latest node-sonos installed
only problem is when using the ADD command
also the admin channel does not work for admin commands

**Comment by htilly** [comment]
Ok, could you please try and get the latest index.js. Changed functions suggested by @vibol.

Please response how it works!

Also note that maxVolume has been added to the config.json.

ps. Fixed the admin commands ds.

BR
Tilly

**Comment by htilly** [comment]
Did it work ?

/Tilly

**Comment by JeromeBouvard** [comment]
No, but I hacked the code manually pretty much everywhere , and now it works :)

**Comment by htilly** [comment]
=)

Like to share the improvements ?! ;)

/Tilly
