### ISSUE TITLE
Setvolume response does not reflect requested volume level

### ISSUE THREAD

**Issue by tonycortex** [htilly/zenmusic#43]
Hi guys, 

When we do setvolume, the response we get back is the previous volume level. 

Should the response show the volume of the request? and not what the level was on previously?

Cheers, Tony

**Comment by htilly** [comment]
Hi! 
That is strange..  It "should" return the newly set volume..  
Everything else is working ok? 
Command "status" return correct value?

BR
Tilly

**Comment by tonycortex** [comment]
Its very strange, all the other commands seem fine.

When we enter "setvolume #requested number", the response we get is "Volume is #previous number..."

**Comment by CaptainAweesome** [comment]
I have the same issue. So everyone knows :)

**Comment by htilly** [comment]
Only thing I can think of is delay between the request and the response..  
Are you running Zenmusic on the same LAN or is it hosted externally?!  I.e. how is the networksetup between the Zenmusic and the Sonos?

/Tilly

**Comment by htilly** [comment]
Hopefully fixed in:
https://github.com/htilly/zenmusic/commit/cc411271339ceb3710223384db7cbc3c3e6b000d
