### ISSUE TITLE
Unable to Search I get an error when I do

### ISSUE THREAD

**Issue by BachDSingh** [htilly/zenmusic#50]
Sorry @BachFromTheFuture, I could not find that track :( same for adding tracks too.

**Comment by macOS-Wolf** [comment]
Same issue here as well, unable to find a solution at the moment :(

**Comment by htilly** [comment]
Hi,

Sorry for my late answer. 
Currently I do not have access to any Sonos so I cant test or verify. Sorry.

**Comment by macOS-Wolf** [comment]
@BachDSingh found the solution, make sure your market is set to the correct country, if you're in the UK use GB instead etc
