### ISSUE TITLE
Issue with the shuffle 

### ISSUE THREAD

**Issue by urvilshahcs** [htilly/zenmusic#51]
the shuffle command is not working. It doesn't throw any error , but doesn't do anything.

**Comment by macOS-Wolf** [comment]
@urvilshahcs does your search/add commands work?

**Comment by urvilshahcs** [comment]
@macOS-Wolf  it does work , only shuffle doesn't work.

**Comment by macOS-Wolf** [comment]
@urvilshahcs interesting, I can't get search or add to work at all, did you make any modifications to the code at all?

**Comment by urvilshahcs** [comment]
@macOS-Wolf  I haven't but I think a quick glance I am seeing the shuffle is on the sonos playlist and I am playing a public spotify channel on the sonos , may be that's the reason ?

**Comment by macOS-Wolf** [comment]
Maybe, I'm surprised you got Spotify to work at all, as it just doesnt seem to work on newer builds

**Comment by htilly** [comment]
A few years later... now "fixed" :)
https://github.com/htilly/zenmusic/commit/2cf427ba64f9ba346ffbdd2ec8a37b6bc6aca937
